name: Respository Dispatch

on: [repository_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform plan
        uses: ./terraform-plan
        with:
          label: repository_dispatch
          path: tests/workflows/repository_dispatch
