name: Create repository_dispatch event

on:
  - pull_request

jobs:
  trigger:
    name: Trigger repository_dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: test
          client-payload: '{"pull_request": { "url": "${{ github.event.pull_request.url }}" } }'
