name: terraform-validate
description: Validate a Terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the workspace to use for the `terraform.workspace` value while validating.
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: 415557941318.dkr.ecr.us-east-1.amazonaws.com/terraform-github-actions:e8e8141a9edb9d5988502a68ba67982ef55e3413
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
