name: tofu-remote-state
description: Retrieve remote state from a backend
author: Daniel Flook

inputs:
  backend_type:
    description: The backend plugin name
    required: true
  workspace:
    description: Name of the OpenTofu workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

runs:
  env:
    OPENTOFU: true
  using: docker
  image: docker://415557941318.dkr.ecr.us-east-1.amazonaws.com/terraform-github-actions:e8e8141a9edb9d5988502a68ba67982ef55e3413
  entrypoint: /entrypoints/remote-state.sh

branding:
  icon: globe
  color: purple
